### ISSUE TITLE
Audio/video issue with discoveryplus.it live streaming

### ISSUE THREAD

**Issue by Ric-82** [Dis90/plugin.video.discoveryplus#40]
Hello,

The add-on works well for content already present on discoveryplus.it, but it works poorly with live streams: the video is very slowed down and the audio appears out of sync. I tried to allow/deny the audio passtrough, and the result is that the audio disappears, but on the other hand the video turns smooth.

**Comment by Dis90** [comment]
Have you tested those streams on website? Add-on itself doesn't do anything to streams or videos it all is handled by Kodi/Inputstream Adaptive.

**Comment by Ric-82** [comment]
> Have you tested those streams on website?

Yes. That is, I can confirm that live streams works well on the website, both from pc and smartphone (I tried with Edge and Firefox). 

I must also point out that the option to enable/disable InputStream Adaptive is grayed out, choosing "discoveryplus.it" in the add-on settings.

**Comment by Dis90** [comment]
> I must also point out that the option to enable/disable InputStream Adaptive is grayed out, choosing "discoveryplus.it" in the add-on settings.

Yeah that option is meant to be used with discovery+ US UHD streams so that is reason why it is greyed out.

Difference between livestreams and other content is that most livestreams are DRM protected so you have to use InputStream Adaptive and other content isn't DRM protected so in theory you doesn't have to use InputStream Adaptive to those videos but subtitles only work with InputStream Adaptive.

Is your hardware powerful enough to play DRM protected streams? You can set resolution down from InputStream Adaptive settings.

**Comment by Ric-82** [comment]
> Is your hardware powerful enough to play DRM protected streams? You can set resolution down from InputStream Adaptive settings.

You're right: I needed to change some settings within the InputStream Adapative add-on. 

Thank you for the advice and the quick assistance.
